apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 362002197926.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 362002197926.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: a932a6d1
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
